name: nuts_activity_indicator
description: Highly customizable activity indicator (spinner) for your Flutter apps based on the cupertino package.
version: 1.0.0
homepage: https://github.com/vincevargadev
repository: https://github.com/dartsidedev/nuts_activity_indicator
issue_tracker: https://github.com/dartsidedev/nuts_activity_indicator/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
